apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-catalog
  labels:
    app: netflix-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-catalog
  template:
    metadata:
        labels:
          app: netflix-catalog
    spec:
      containers:
      - name: server
        image: davidhei/netflix:catalog-v0.0.2