apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-frontend
  labels:
    app: netflix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-frontend
  template:
    metadata:
        labels:
          app: netflix-frontend
    spec:
      containers:
      - name: server
        image: davidhei/netflix:frontend-v0.0.3
        env:
          - name: MOVIE_CATALOG_SERVICE
            value: http://netflix-catalog-service:8080
          - name: REDIS_URL
            value: redis-service:6379
